# Generated by Django 4.1.2 on 2023-05-12 18:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('ACCOUNT', 'ACCOUNT'), ('FINANCE', 'FINANCE'), ('HR', 'HR'), ('MARKETING', 'MARKETING'), ('OPERATION', 'OPERATION'), ('SALES', 'SALES'), ('IT', 'IT')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('DOB', models.DateField(editable=False)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=255)),
                ('is_working', models.BooleanField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.department')),
            ],
        ),
    ]
